name: bump version pr
on:
  push:
    branches:
      - update-*
jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: pull-request
      uses: repo-sync/pull-request@v2
      with:
        destination_branch: "main"
        pr_label: "pr-pull"
        github_token: ${{ secrets.GITHUB_TOKEN }}